# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sectionBuilder.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,5}")
        input_validator = QtGui.QRegExpValidator(reg_ex)        
        Dialog.setObjectName("Dialog")
        Dialog.resize(756, 429)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(401, 371))
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 0, 0, 3, 1)
        self.shapes = QtWidgets.QComboBox(Dialog)
        self.shapes.setObjectName("shapes")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.gridLayout_2.addWidget(self.shapes, 0, 1, 1, 2)
        self.sectionName = QtWidgets.QLineEdit(Dialog)
        self.sectionName.setObjectName("sectionName")
        self.gridLayout_2.addWidget(self.sectionName, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.length = QtWidgets.QLineEdit(self.groupBox)
        self.length.setObjectName("length")
        self.gridLayout.addWidget(self.length, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.breadth = QtWidgets.QLineEdit(self.groupBox)
        self.breadth.setObjectName("breadth")
        self.gridLayout.addWidget(self.breadth, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.flanges = QtWidgets.QLineEdit(self.groupBox)
        self.flanges.setObjectName("flanges")
        self.gridLayout.addWidget(self.flanges, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.width = QtWidgets.QLineEdit(self.groupBox)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 1, 3, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 3)
        self.output = QtWidgets.QTextBrowser(Dialog)
        self.output.setObjectName("output")
        self.gridLayout_2.addWidget(self.output, 2, 1, 1, 3)
        self.calculate = QtWidgets.QPushButton(Dialog)
        self.calculate.setObjectName("calculate")
        self.gridLayout_2.addWidget(self.calculate, 3, 1, 1, 1)
        self.saveSection = QtWidgets.QPushButton(Dialog)
        self.saveSection.setObjectName("saveSection")
        self.gridLayout_2.addWidget(self.saveSection, 3, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 3, 1, 1)
        self.length.setValidator(input_validator)
        self.breadth.setValidator(input_validator)
        self.flanges.setValidator(input_validator)
        self.width.setValidator(input_validator)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Section Designer"))
        self.shapes.setItemText(0, _translate("Dialog", "Rectangle"))
        self.shapes.setItemText(1, _translate("Dialog", "Square"))
        self.shapes.setItemText(2, _translate("Dialog", "Circle"))
        self.shapes.setItemText(3, _translate("Dialog", "I"))
        self.shapes.setItemText(4, _translate("Dialog", "T"))
        self.shapes.setItemText(5, _translate("Dialog", "C"))
        self.shapes.setItemText(6, _translate("Dialog", "L"))
        self.shapes.setItemText(7, _translate("Dialog", "Hollow Rectangle"))
        self.shapes.setItemText(8, _translate("Dialog", "Hollow Square"))
        self.shapes.setItemText(9, _translate("Dialog", "Hollow Circle"))
        self.sectionName.setPlaceholderText(_translate("Dialog", "Name of section"))
        self.groupBox.setTitle(_translate("Dialog", "GroupBox"))
        self.label.setText(_translate("Dialog", "l/d"))
        self.length.setPlaceholderText(_translate("Dialog", "length/diameter"))
        self.label_2.setText(_translate("Dialog", "b"))
        self.breadth.setPlaceholderText(_translate("Dialog", "breadth"))
        self.label_3.setText(_translate("Dialog", "f"))
        self.flanges.setPlaceholderText(_translate("Dialog", "flanges"))
        self.label_4.setText(_translate("Dialog", "w"))
        self.width.setPlaceholderText(_translate("Dialog", "width"))
        self.calculate.setText(_translate("Dialog", "Calculate"))
        self.saveSection.setText(_translate("Dialog", "Save"))
