# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sectionDesigner.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets
from sampleDatas import resource_path


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 3, 3, 1, 1)
        self.output = QtWidgets.QTextBrowser(self.tab)
        self.output.setObjectName("output")
        self.gridLayout_3.addWidget(self.output, 2, 1, 1, 3)
        self.calculate = QtWidgets.QPushButton(self.tab)
        self.calculate.setObjectName("calculate")
        self.gridLayout_3.addWidget(self.calculate, 3, 1, 1, 1)
        self.saveSection = QtWidgets.QPushButton(self.tab)
        self.saveSection.setObjectName("saveSection")
        self.gridLayout_3.addWidget(self.saveSection, 3, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.length = QtWidgets.QLineEdit(self.groupBox)
        self.length.setObjectName("length")
        self.gridLayout.addWidget(self.length, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 2)
        self.breadth = QtWidgets.QLineEdit(self.groupBox)
        self.breadth.setObjectName("breadth")
        self.gridLayout.addWidget(self.breadth, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.flanges = QtWidgets.QLineEdit(self.groupBox)
        self.flanges.setObjectName("flanges")
        self.gridLayout.addWidget(self.flanges, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.width = QtWidgets.QLineEdit(self.groupBox)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 1, 3, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox, 1, 1, 1, 3)
        self.sectionName = QtWidgets.QLineEdit(self.tab)
        self.sectionName.setObjectName("sectionName")
        self.gridLayout_3.addWidget(self.sectionName, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 4, 1, 1)
        self.shapes = QtWidgets.QComboBox(self.tab)
        self.shapes.setObjectName("shapes")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.shapes.addItem("")
        self.gridLayout_3.addWidget(self.shapes, 0, 1, 1, 2)
        self.image = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMinimumSize(QtCore.QSize(401, 371))
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout_3.addWidget(self.image, 0, 0, 4, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLine = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("./ico/Tools/toolline.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionLine.setIcon(icon)
        self.actionLine.setObjectName("actionLine")
        self.actionarc = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("./ico/Tools/toolarc.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionarc.setIcon(icon1)
        self.actionarc.setObjectName("actionarc")
        
        self.actionquad = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("./ico/Tools/toolquad.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionquad.setIcon(icon2)
        self.actionquad.setObjectName("actionquad")


        self.actionDesign = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("./ico/Tools/toolsection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDesign.setIcon(icon2)
        self.actionDesign.setObjectName("actionDesign")
        
        self.toolBar.addAction(self.actionLine)
        self.toolBar.addAction(self.actionarc)
        self.toolBar.addAction(self.actionquad)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDesign)


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Section Desinger"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.saveSection.setText(_translate("MainWindow", "Save"))
        self.groupBox.setTitle(_translate("MainWindow", "Dimensions"))
        self.label.setText(_translate("MainWindow", "l/d"))
        self.length.setPlaceholderText(_translate("MainWindow", "length/diameter"))
        self.label_2.setText(_translate("MainWindow", "b"))
        self.breadth.setPlaceholderText(_translate("MainWindow", "breadth"))
        self.label_3.setText(_translate("MainWindow", "f"))
        self.flanges.setPlaceholderText(_translate("MainWindow", "flanges"))
        self.label_4.setText(_translate("MainWindow", "w"))
        self.width.setPlaceholderText(_translate("MainWindow", "width"))
        self.sectionName.setPlaceholderText(_translate("MainWindow", "Name of section"))
        self.shapes.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.shapes.setItemText(1, _translate("MainWindow", "Square"))
        self.shapes.setItemText(2, _translate("MainWindow", "Circle"))
        self.shapes.setItemText(3, _translate("MainWindow", "I"))
        self.shapes.setItemText(4, _translate("MainWindow", "T"))
        self.shapes.setItemText(5, _translate("MainWindow", "C"))
        self.shapes.setItemText(6, _translate("MainWindow", "L"))
        self.shapes.setItemText(7, _translate("MainWindow", "Hollow Rectangle"))
        self.shapes.setItemText(8, _translate("MainWindow", "Hollow Square"))
        self.shapes.setItemText(9, _translate("MainWindow", "Hollow Circle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Design Standard Sections"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Design Custom Section"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionLine.setToolTip(_translate("MainWindow", "Draw line select 2 points"))
        self.actionLine.setShortcut(_translate("MainWindow", "L"))
        self.actionarc.setText(_translate("MainWindow", "arc"))
        self.actionarc.setToolTip(_translate("MainWindow", "Draw arc with 3 points"))
        self.actionarc.setShortcut(_translate("MainWindow", "A"))
        self.actionquad.setText(_translate("MainWindow", "quad"))
        self.actionquad.setToolTip(_translate("MainWindow", "Draw parabola with 3 points"))
        self.actionquad.setShortcut(_translate("MainWindow", "Q"))

        self.actionDesign.setText(_translate("MainWindow", "Design"))
        self.actionDesign.setToolTip(_translate("MainWindow", "Design the section"))
        self.actionDesign.setShortcut(_translate("MainWindow", "D"))
