# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newUnitWindow.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(347, 346)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.SIunits = QtWidgets.QRadioButton(Dialog)
        self.SIunits.setChecked(True)
        self.SIunits.setObjectName("SIunits")
        self.gridLayout.addWidget(self.SIunits, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.SIunitOfForce = QtWidgets.QComboBox(self.groupBox)
        self.SIunitOfForce.setObjectName("SIunitOfForce")
        self.gridLayout_2.addWidget(self.SIunitOfForce, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.SIforceMagnitude = QtWidgets.QLineEdit(self.groupBox)
        self.SIforceMagnitude.setEnabled(True)
        self.SIforceMagnitude.setReadOnly(True)
        self.SIforceMagnitude.setObjectName("SIforceMagnitude")
        self.gridLayout_2.addWidget(self.SIforceMagnitude, 0, 3, 1, 2)
        self.forceSuffix = QtWidgets.QLabel(self.groupBox)
        self.forceSuffix.setObjectName("forceSuffix")
        self.gridLayout_2.addWidget(self.forceSuffix, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.SIunitOfLength = QtWidgets.QComboBox(self.groupBox)
        self.SIunitOfLength.setObjectName("SIunitOfLength")
        self.gridLayout_2.addWidget(self.SIunitOfLength, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 2, 1, 1)
        self.SIlengthMagnitude = QtWidgets.QLineEdit(self.groupBox)
        self.SIlengthMagnitude.setEnabled(True)
        self.SIlengthMagnitude.setReadOnly(True)
        self.SIlengthMagnitude.setObjectName("SIlengthMagnitude")
        self.gridLayout_2.addWidget(self.SIlengthMagnitude, 1, 3, 1, 2)
        self.lengthSuffix = QtWidgets.QLabel(self.groupBox)
        self.lengthSuffix.setObjectName("lengthSuffix")
        self.gridLayout_2.addWidget(self.lengthSuffix, 1, 5, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 6)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.SIunitOfScale = QtWidgets.QComboBox(self.groupBox)
        self.SIunitOfScale.setObjectName("SIunitOfScale")
        self.gridLayout_2.addWidget(self.SIunitOfScale, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 2, 1, 2)
        self.SIprecison = QtWidgets.QSpinBox(self.groupBox)
        self.SIprecison.setProperty("value", 8)
        self.SIprecison.setObjectName("SIprecison")
        self.gridLayout_2.addWidget(self.SIprecison, 3, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.ENGunits = QtWidgets.QRadioButton(Dialog)
        self.ENGunits.setChecked(False)
        self.ENGunits.setObjectName("ENGunits")
        self.gridLayout.addWidget(self.ENGunits, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ENGlengthMagnitude = QtWidgets.QLineEdit(self.groupBox_2)
        self.ENGlengthMagnitude.setEnabled(False)
        self.ENGlengthMagnitude.setReadOnly(True)
        self.ENGlengthMagnitude.setObjectName("ENGlengthMagnitude")
        self.gridLayout_3.addWidget(self.ENGlengthMagnitude, 1, 3, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.ENGunitOfLength = QtWidgets.QComboBox(self.groupBox_2)
        self.ENGunitOfLength.setObjectName("ENGunitOfLength")
        self.gridLayout_3.addWidget(self.ENGunitOfLength, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 2, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.ENGprecison = QtWidgets.QSpinBox(self.groupBox_2)
        self.ENGprecison.setProperty("value", 8)
        self.ENGprecison.setObjectName("ENGprecison")
        self.gridLayout_3.addWidget(self.ENGprecison, 3, 4, 1, 1)
        self.ENGforceMagnitude = QtWidgets.QLineEdit(self.groupBox_2)
        self.ENGforceMagnitude.setEnabled(False)
        self.ENGforceMagnitude.setReadOnly(True)
        self.ENGforceMagnitude.setClearButtonEnabled(False)
        self.ENGforceMagnitude.setObjectName("ENGforceMagnitude")
        self.gridLayout_3.addWidget(self.ENGforceMagnitude, 0, 3, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.forceSuffix_2 = QtWidgets.QLabel(self.groupBox_2)
        self.forceSuffix_2.setObjectName("forceSuffix_2")
        self.gridLayout_3.addWidget(self.forceSuffix_2, 0, 5, 1, 1)
        self.lengthSuffix_2 = QtWidgets.QLabel(self.groupBox_2)
        self.lengthSuffix_2.setObjectName("lengthSuffix_2")
        self.gridLayout_3.addWidget(self.lengthSuffix_2, 1, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.ENGunitOfForce = QtWidgets.QComboBox(self.groupBox_2)
        self.ENGunitOfForce.setObjectName("ENGunitOfForce")
        self.gridLayout_3.addWidget(self.ENGunitOfForce, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 2)
        self.ENGunitOfScale = QtWidgets.QComboBox(self.groupBox_2)
        self.ENGunitOfScale.setObjectName("ENGunitOfScale")
        self.gridLayout_3.addWidget(self.ENGunitOfScale, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 2)
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 4, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.SIunits.toggled['bool'].connect(self.groupBox.setEnabled)
        self.ENGunits.toggled['bool'].connect(self.groupBox_2.setEnabled)
        self.cancel.clicked.connect(Dialog.reject)
        self.ENGunits.clicked['bool'].connect(self.ENGforceMagnitude.setEnabled)
        self.ENGunits.clicked['bool'].connect(self.ENGlengthMagnitude.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Units"))
        self.SIunits.setText(_translate("Dialog", "SI Units"))
        self.label.setText(_translate("Dialog", "Force"))
        self.label_7.setText(_translate("Dialog", "="))
        self.SIforceMagnitude.setText(_translate("Dialog", "1"))
        self.forceSuffix.setText(_translate("Dialog", "N"))
        self.label_4.setText(_translate("Dialog", "Length"))
        self.label_8.setText(_translate("Dialog", "="))
        self.SIlengthMagnitude.setText(_translate("Dialog", "1"))
        self.lengthSuffix.setText(_translate("Dialog", "m"))
        self.label_5.setText(_translate("Dialog", "Scale"))
        self.SIunitOfScale.setToolTip(_translate("Dialog", "Select scale for ploting graph"))
        self.label_6.setText(_translate("Dialog", "Precison"))
        self.SIprecison.setToolTip(_translate("Dialog", "Significant figures for all the results"))
        self.ENGunits.setText(_translate("Dialog", "Engineering Units"))
        self.ENGlengthMagnitude.setText(_translate("Dialog", "1"))
        self.label_13.setText(_translate("Dialog", "="))
        self.label_2.setText(_translate("Dialog", "Force"))
        self.ENGprecison.setToolTip(_translate("Dialog", "Significant figures for all the results"))
        self.ENGforceMagnitude.setText(_translate("Dialog", "1"))
        self.label_11.setText(_translate("Dialog", "Scale"))
        self.forceSuffix_2.setText(_translate("Dialog", "pdl"))
        self.lengthSuffix_2.setText(_translate("Dialog", "ft"))
        self.label_9.setText(_translate("Dialog", "="))
        self.label_10.setText(_translate("Dialog", "Length"))
        self.label_12.setText(_translate("Dialog", "Precison"))
        self.ENGunitOfScale.setToolTip(_translate("Dialog", "Select scale for ploting graph"))
        self.save.setText(_translate("Dialog", "Save"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
