# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segmentDialog.ui'
#
# Created by: PySide2 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        reg_ex = QtCore.QRegExp("[0-9]+.?[0-9]{,5}")
        input_validator = QtGui.QRegExpValidator(reg_ex)
        Dialog.setObjectName("Dialog")
        Dialog.resize(654, 384)
        Dialog.setMinimumSize(QtCore.QSize(654, 384))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 384))
        Dialog.setAccessibleName("")
        Dialog.setSizeGripEnabled(False)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout_4.addWidget(self.name, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.p1x = QtWidgets.QLineEdit(Dialog)
        self.p1x.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p1x.setValidator(input_validator)
        self.p1x.setObjectName("p1x")
        self.gridLayout.addWidget(self.p1x, 1, 1, 1, 1)
        self.p1y = QtWidgets.QLineEdit(Dialog)
        self.p1y.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p1y.setValidator(input_validator)
        self.p1y.setObjectName("p1y")
        self.gridLayout.addWidget(self.p1y, 1, 2, 1, 1)
        self.p1z = QtWidgets.QLineEdit(Dialog)
        self.p1z.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p1z.setValidator(input_validator)
        self.p1z.setObjectName("p1z")
        self.gridLayout.addWidget(self.p1z, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.p2x = QtWidgets.QLineEdit(Dialog)
        self.p2x.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p2x.setValidator(input_validator)
        self.p2x.setObjectName("p2x")
        self.gridLayout.addWidget(self.p2x, 2, 1, 1, 1)
        self.p2y = QtWidgets.QLineEdit(Dialog)
        self.p2y.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p2y.setValidator(input_validator)
        self.p2y.setObjectName("p2y")
        self.gridLayout.addWidget(self.p2y, 2, 2, 1, 1)
        self.p2z = QtWidgets.QLineEdit(Dialog)
        self.p2z.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p2z.setValidator(input_validator)
        self.p2z.setObjectName("p2z")
        self.gridLayout.addWidget(self.p2z, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.p3x = QtWidgets.QLineEdit(Dialog)
        self.p3x.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p3x.setValidator(input_validator)
        self.p3x.setObjectName("p3x")
        self.gridLayout.addWidget(self.p3x, 3, 1, 1, 1)
        self.p3y = QtWidgets.QLineEdit(Dialog)
        self.p3y.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p3y.setValidator(input_validator)
        self.p3y.setObjectName("p3y")
        self.gridLayout.addWidget(self.p3y, 3, 2, 1, 1)
        self.p3z = QtWidgets.QLineEdit(Dialog)
        self.p3z.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.p3z.setText("")
        self.p3z.setObjectName("p3z")
        self.p3z.setValidator(input_validator)
        self.gridLayout.addWidget(self.p3z, 3, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.iyy = QtWidgets.QLineEdit(Dialog)
        self.iyy.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.iyy.setObjectName("iyy")
        self.gridLayout_3.addWidget(self.iyy, 3, 1, 1, 1)
        self.area = QtWidgets.QLineEdit(Dialog)
        self.area.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.area.setObjectName("area")
        self.gridLayout_3.addWidget(self.area, 1, 1, 1, 1)
        self.shapeFactor = QtWidgets.QLineEdit(Dialog)
        self.shapeFactor.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.shapeFactor.setObjectName("shapeFactor")
        self.gridLayout_3.addWidget(self.shapeFactor, 3, 3, 1, 1)
        self.torsionConstant = QtWidgets.QLineEdit(Dialog)
        self.torsionConstant.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.torsionConstant.setObjectName("torsionConstant")
        self.gridLayout_3.addWidget(self.torsionConstant, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 3, 1, 1)
        self.segmentSection = QtWidgets.QComboBox(Dialog)
        self.segmentSection.setObjectName("segmentSection")
        self.gridLayout_3.addWidget(self.segmentSection, 1, 0, 1, 1)
        self.axisVector = QtWidgets.QLineEdit(Dialog)
        self.axisVector.setStatusTip("")
        self.axisVector.setObjectName("axisVector")
        self.gridLayout_3.addWidget(self.axisVector, 1, 3, 1, 1)
        self.ixx = QtWidgets.QLineEdit(Dialog)
        self.ixx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.ixx.setObjectName("ixx")
        self.gridLayout_3.addWidget(self.ixx, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 5, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 2, 0, 1, 5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.segmentMaterial = QtWidgets.QComboBox(Dialog)
        self.segmentMaterial.setObjectName("segmentMaterial")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.segmentMaterial.addItem("")
        self.gridLayout_2.addWidget(self.segmentMaterial, 1, 0, 1, 1)
        self.youngsModulus = QtWidgets.QLineEdit(Dialog)
        self.youngsModulus.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.youngsModulus.setObjectName("youngsModulus")
        self.gridLayout_2.addWidget(self.youngsModulus, 1, 1, 1, 1)
        self.shearModulus = QtWidgets.QLineEdit(Dialog)
        self.shearModulus.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.shearModulus.setObjectName("shearModulus")
        self.gridLayout_2.addWidget(self.shearModulus, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 4, 0, 1, 5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 6, 4, 1, 1)
        self.buttonBox.raise_()
        self.label.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.name.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.p1x, self.p1y)
        Dialog.setTabOrder(self.p1y, self.p1z)
        Dialog.setTabOrder(self.p1z, self.p2x)
        Dialog.setTabOrder(self.p2x, self.p2y)
        Dialog.setTabOrder(self.p2y, self.p2z)
        Dialog.setTabOrder(self.p2z, self.p3x)
        Dialog.setTabOrder(self.p3x, self.p3y)
        Dialog.setTabOrder(self.p3y, self.p3z)
        Dialog.setTabOrder(self.p3z, self.youngsModulus)
        Dialog.setTabOrder(self.youngsModulus, self.shearModulus)
        Dialog.setTabOrder(self.shearModulus, self.area)
        Dialog.setTabOrder(self.area, self.ixx)
        Dialog.setTabOrder(self.ixx, self.axisVector)
        Dialog.setTabOrder(self.axisVector, self.iyy)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Segement Detials"))
        self.name.setPlaceholderText(_translate("Dialog", "Name of the segment (optional)"))
        self.label_2.setText(_translate("Dialog", "Initial Point"))
        self.p1x.setPlaceholderText(_translate("Dialog", "x"))
        self.p1y.setPlaceholderText(_translate("Dialog", "y"))
        self.p1z.setPlaceholderText(_translate("Dialog", "z"))
        self.label_3.setText(_translate("Dialog", "Terminal Point"))
        self.p2x.setPlaceholderText(_translate("Dialog", "x"))
        self.p2y.setPlaceholderText(_translate("Dialog", "y"))
        self.p2z.setPlaceholderText(_translate("Dialog", "z"))
        self.label_4.setText(_translate("Dialog", "Intermediate Point"))
        self.p3x.setPlaceholderText(_translate("Dialog", "x"))
        self.p3y.setPlaceholderText(_translate("Dialog", "y"))
        self.p3z.setPlaceholderText(_translate("Dialog", "z"))
        self.iyy.setStatusTip(_translate("Dialog", "Axis of Iyy should be perpendicular to axis of Ixx"))
        self.iyy.setPlaceholderText(_translate("Dialog", "I about centroid"))
        self.area.setPlaceholderText(_translate("Dialog", "CSA of segment"))
        self.shapeFactor.setStatusTip(_translate("Dialog", "Axis of Iyy should be perpendicular to axis of Ixx"))
        self.shapeFactor.setPlaceholderText(_translate("Dialog", "shape factor"))
        self.torsionConstant.setStatusTip(_translate("Dialog", "Axis of Iyy should be perpendicular to axis of Ixx"))
        self.torsionConstant.setPlaceholderText(_translate("Dialog", "about centroid"))
        self.label_10.setText(_translate("Dialog", "Iyy"))
        self.label_7.setText(_translate("Dialog", "A"))
        self.label_15.setText(_translate("Dialog", "Shape factor(k)"))
        self.label_9.setText(_translate("Dialog", "Axis vector"))
        self.axisVector.setPlaceholderText(_translate("Dialog", "Axis of Ixx (x,y,z)"))
        self.ixx.setPlaceholderText(_translate("Dialog", "I about centroid"))
        self.label_14.setText(_translate("Dialog", "Torsion constant"))
        self.label_12.setText(_translate("Dialog", "Section"))
        self.label_8.setText(_translate("Dialog", "Ixx"))
        self.label_11.setText(_translate("Dialog", "Material"))
        self.label_5.setText(_translate("Dialog", "E"))
        self.label_6.setText(_translate("Dialog", "G"))
        self.segmentMaterial.setItemText(0, _translate("Dialog", "--Select--"))
        self.segmentMaterial.setItemText(1, _translate("Dialog", "Steel HR"))
        self.segmentMaterial.setItemText(2, _translate("Dialog", "Stainless Steel"))
        self.segmentMaterial.setItemText(3, _translate("Dialog", "Concrete LS"))
        self.segmentMaterial.setItemText(4, _translate("Dialog", "Concrete MS"))
        self.segmentMaterial.setItemText(5, _translate("Dialog", "Concrete HS"))
        self.segmentMaterial.setItemText(6, _translate("Dialog", "Cast iron Gray"))
        self.segmentMaterial.setItemText(7, _translate("Dialog", "Cast iron Malleable"))
        self.segmentMaterial.setItemText(8, _translate("Dialog", "Aluminium"))
        self.segmentMaterial.setItemText(9, _translate("Dialog", "Glass Silicon"))
        self.segmentMaterial.setItemText(10, _translate("Dialog", "Copper"))
        self.segmentMaterial.setItemText(11, _translate("Dialog", "Bronze"))
        self.segmentMaterial.setItemText(12, _translate("Dialog", "Brass"))
        self.youngsModulus.setPlaceholderText(_translate("Dialog", "Young\'s Modulus"))
        self.shearModulus.setPlaceholderText(_translate("Dialog", "Shear Modulus"))
        self.label.setText(_translate("Dialog", "Name"))
